### ISSUE TITLE
Error when build in Prod

### ISSUE THREAD

**Issue by Shmasya** [alxhotel/angular-bigscreen#1]
When run script ng build --prod this service return error:
ERROR in Error: Unexpected value 'BigScreenService in /node_modules/angular-bigscreen/bigscreen.service.d.ts' declared by th
e module 'BigScreenModule in /node_modules/angular-bigscreen/bigscreen.module.d.ts'. Please add a @Pipe/@Directive/@Componen
t annotation.

**Comment by alxhotel** [comment]
Thanks for the feedback!

Can you try the new version 2.0.0?

**Comment by Shmasya** [comment]
@alxhotel i migrate to another lib https://github.com/sindresorhus/screenfull.js

**Comment by alxhotel** [comment]
Ok, no problem. Btw, sorry for the delay.

Closing this issue then.
